{-
   The Plaid API

   The Plaid REST API. Please see https://plaid.com/docs/api for more details.

   OpenAPI Version: 3.0.0
   The Plaid API API version: 2020-09-14_1.8.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : ThePlaid.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module ThePlaid.Logging
  ( module ThePlaid.LoggingKatip
  ) where

import ThePlaid.LoggingKatip

#else

module ThePlaid.Logging
  ( module ThePlaid.LoggingMonadLogger
  ) where

import ThePlaid.LoggingMonadLogger

#endif
